META_ARC: "siammaskrcnn_feature_enhance_dcnv1"

BACKBONE:
    TYPE: "resnet50"
    KWARGS:
        used_layers: [0, 1, 2, 3, 4]
    PRETRAINED: 'pretrained/resnet.pth'
    TRAIN_LAYERS: ['layer2', 'layer3', 'layer4']
    TRAIN_EPOCH: 10
    LAYERS_LR: 0.05

ADJUST:
    ADJUST: true
    TYPE: "AdjustAllLayer"
    KWARGS:
        in_channels: [512, 1024, 2048]
        out_channels: [256, 256, 256]

RPN:
    TYPE: 'MultiRPN'
    KWARGS:
        anchor_num: 5
        in_channels: [256, 256, 256]
        weighted: true

MASK:
    MASK: True
    KWARGS:
        in_channels: [256, 256, 256, 256]   

ANCHOR:
    STRIDE: 8
    RATIOS: [0.33, 0.5, 1, 2, 3]
    SCALES: [8]
    ANCHOR_NUM: 5

TRACK:
    TYPE: 'SiamMaskTracker'
    PENALTY_K: 0.20
    WINDOW_INFLUENCE: 0.350
    LR: 0.500
    EXEMPLAR_SIZE: 127
    INSTANCE_SIZE: 255
    BASE_SIZE: 8
    CONTEXT_AMOUNT: 0.5
    MASK_THERSHOLD: 0.2
    MASK_OUTPUT_SIZE: 64
    
TRAIN:
    LOG_GRADS: FALSE
    EPOCH: 20
    START_EPOCH: 0
    BATCH_SIZE: 11
    ROI_PER_IMG: 15
    BASE_LR: 0.005
    CLS_WEIGHT: 5.0
    LOC_WEIGHT: 1.2
    MASK_WEIGHT: 0.5
    BBOX_WEIGHT: 1.0
    RESUME: ''

    LR:
        TYPE: 'log'
        KWARGS:
            start_lr: 0.005
            end_lr: 0.0005
    LR_WARMUP:
        TYPE: 'step'
        EPOCH: 5
        KWARGS:
            start_lr: 0.001
            end_lr: 0.005
            step: 1

DATASET:
    GRAY: 0.2
